#!/usr/bin/env bash

file=$1
w=$2
h=$3
x=$4
y=$5

preview() {
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
}

TEMPDIR=$HOME/.cache

file="$1"; shift
case "$(basename "$file" | tr '[A-Z]' '[a-z]')" in
*.a|*.ace|*.alz|*.arc|*.arj|*.bz|*.bz2|*.cab|*.cpio|*.deb|*.gz|*.jar|*.lha|*.lz|*.lzh|*.lzma|*.lzo|*.rpm|*.rz|*.t7z|*.tar|*.tbz|*.tbz2|*.tgz|*.tlz|*.txz|*.tZ|*.tzo|*.war|*.xpi|*.xz|*.Z|*.zip) 
	atool --list -- "$file" && exit 5
    bsdtar --list --file "$file" && exit 5
    exit 1
;;
*.ear|*.oxt) 
	unzip -l "$file"
;;
*.rar) 
	## Avoid password prompt by providing empty password
	unrar lt -p- -- "$file" && exit 5
    exit 1
;;
*.7z) 
	## Avoid password prompt by providing empty password
	7z l -p -- "$file" && exit 5
    exit 1
;;
*.torrent)
	transmission-show -- "$file" && exit 5
    exit 1
;;
*.odt|*.ods|*.odp|*.sxw)
	## Preview as text conversion
	odt2txt "$file" && exit 5
	## Preview as markdown conversion
	pandoc -s -t markdown -- "$file" && exit 5
	exit 1
;;
*.xls|*.xlsx)
	## Preview as csv conversion
	## Uses: https://github.com/dilshod/xlsx2csv
	xlsx2csv -- "$file" && exit 5
	exit 1
;;
*.xml|*.htm|*.html|*.xhtml)
	## Preview as text conversion
	w3m -dump "$file" && exit 5
	lynx -dump -- "$file" && exit 5
	elinks -dump "$file" && exit 5
	pandoc -s -t markdown -- "$file" && exit 5
;;
*.json)
	jq --color-output . "$file" && exit 5
	python -m json.tool -- "$file" && exit 5
;;
*.dff|*.dsf|*.wv|*.wvc)
	mediainfo "$file" && exit 5
	exiftool "$file" && exit 5
;;
*.doc|*.rtf)
	catdoc -- "$file" && exit 5
    exit 1
;;
*.docx|*.epub|*.fb2)
	pandoc -s -t markdown -- "$file" && exit 5
    exit 1
;;
*.[1-8]) 
	man "$file" | col -b 
;;
*.o)
	nm "$file"
;;
*.iso)
	iso-info --no-header -l "$file"
;;
*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
	thumbnail="$TEMPDIR/thumbnail.png"
	ffmpeg -y -i "$file" -vframes 1 "$thumbnail"
    preview "$thumbnail"
;;
*.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.mka)
	exiftool "$file"
;;
*.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp|*.tiff|*.gif|*.jfif|*.ico)
    preview "$file"
;;
*.ttf|*.otf|*.woff)
	thumbnail="$TEMPDIR/thumbnail.png"
	fontpreview -i "$file" -o "$thumbnail"
	preview "$thumbnail"
;;
*.svg)
	thumbnail="$TEMPDIR/thumbnail.png"
	convert "$file" "$thumbnail"
	preview "$thumbnail"
;;
*.pdf)
	thumbnail="$TEMPDIR/thumbnail.png"
	gs -o "$thumbnail" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
    preview "$thumbnail"
;;
*)
	pistol "$file"
	# bat --color=always --style=plain --pager=never "$file" "$@"
;;
esac
return 127 # nonzero retcode required for lf previews to reload