# Alacritty - TOML configuration file.

import = ["/home/anisbsalah/.config/alacritty/colors.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 12.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[window]
opacity = 0.9
startup_mode = "Maximized"
position = { x = 0, y = 0 }

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.15

[selection]
save_to_clipboard = true

[scrolling]
history = 50000

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "T", mods = "Control|Shift", action = "CreateNewWindow" },
]
