# Colors (Sweet)

# Default colors
[colors.primary]
background = '0x161925'
foreground = '0xC3C7D1'

dim_foreground    = '0xC3C7D1'
bright_foreground = '0xC3C7D1'

# Cursor colors
[colors.cursor]
text   = '0x161925'
cursor = '0xC3C7D1'

# Normal colors
[colors.normal]
black   = '0x282C34'
red     = '0xED254E'
green   = '0x71F79F'
yellow  = '0xF9DC5C'
blue    = '0x7CB7FF'
magenta = '0xC74DED'
cyan    = '0x00C1E4'
white   = '0xDCDFE4'

# Bright colors
[colors.bright]
black   = '0x282C34'
red     = '0xED254E'
green   = '0x71F79F'
yellow  = '0xF9DC5C'
blue    = '0x7CB7FF'
magenta = '0xC74DED'
cyan    = '0x00C1E4'
white   = '0xDCDFE4'

# Dim colors
[colors.dim]
black   = '0x282C34'
red     = '0xED254E'
green   = '0x71F79F'
yellow  = '0xF9DC5C'
blue    = '0x7CB7FF'
magenta = '0xC74DED'
cyan    = '0x00C1E4'
white   = '0xDCDFE4'
