#!/usr/bin/env bash
#
# Script name: dmconf
# Description: Choose from a list of configuration files to edit.
# Dependencies: dmenu
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# Contributors: Derek Taylor

# Defining the text editor to use.
DMEDITOR="subl"

# An array of options to choose.
# You can edit this list to add/remove config files.
declare -a options=(
	"bashrc - ${HOME}/.bashrc"
	"bash_aliases - ${HOME}/.bash_aliases"
	"fish_config - ${HOME}/.config/fish/config.fish"
	"fish_aliases - ${HOME}/.config/fish/fish_aliases"
	"fstab - /etc/fstab"
	"grub - /etc/default/grub"
	"zshrc - ${HOME}/.config/zsh/.zshrc"
	"zsh_aliases - ${HOME}/.config/zsh/zsh_aliases"
	"Quit"
)

# Piping the above array into dmenu.
# We use "printf '%s\n'" to format the array one item to a line.
CHOICE=$(printf '%s\n' "${options[@]}" | dmenu -i -l 10 -p 'Config files:')

# What to do when/if we choose 'quit'.
if [[ ${CHOICE} == "Quit" ]]; then
	echo "Program terminated." && exit 1

# What to do when/if we choose a file to edit.
elif [[ -n ${CHOICE} ]]; then
	cfg=$(printf '%s\n' "${CHOICE}" | awk '{print $NF}')
	${DMEDITOR} "${cfg}"

# What to do if we just escape without choosing anything.
else
	echo "Program terminated." && exit 1
fi
